##################################################################################################
# Rules Decision services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{  .Chart.Name }}
  labels:
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: {{  .Chart.Name }}
    meta.helm.sh/release-namespace: default
    app: {{  .Chart.Name }}
    service: {{  .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.rulesdecision.service.servicePort }}
    name: http
  selector:
    app: {{  .Chart.Name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{  .Chart.Name }}
  labels:
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: {{  .Chart.Name }}
    meta.helm.sh/release-namespace: default
    account: {{  .Chart.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Chart.Name }}-{{  .Values.rulesdecision.version }}
  labels:
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: {{  .Chart.Name }}
    meta.helm.sh/release-namespace: default
    app: {{  .Chart.Name }}
    version: {{  .Values.rulesdecision.version }}
spec:
  replicas: {{  .Values.rulesdecision.replicaCount }}
  selector:
    matchLabels:
      app: {{  .Chart.Name }}
      version: {{  .Values.rulesdecision.version }}
  template:
    metadata:
      labels:
        app: {{  .Chart.Name }}
        version: {{  .Values.rulesdecision.version }}
    spec:
      serviceAccountName: {{  .Chart.Name }}
      containers:
      - name: {{  .Chart.Name }}
        image: {{ .Values.rulesdecision.image.repository }}:{{ .Values.rulesdecision.image.tag }}
        imagePullPolicy: {{ .Values.rulesdecision.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.rulesdecision.service.servicePort}}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      imagePullSecrets:
        - name: {{ .Values.imagepullsecrets.name}}
      volumes:
      - name: tmp
        emptyDir: {}
---